### ISSUE TITLE
Issues from multiple files do not show up in same list in neovim

### ISSUE THREAD

**Issue by polarmutex** [polarmutex/beancount-language-server#1]

**Comment by bryall** [comment]
I think to solve this you will need to have a custom publishDiagnostics funvtion on the LSP client

Issues to look into
[LSP/references: Add context to locations returned by server](https://github.com/neovim/neovim/pull/11910)
[LSP: Expose diagnostics grouped by bufnr and line](https://github.com/neovim/neovim/pull/11932)
