### ISSUE TITLE
Language server does not start when configured with Nvim LSP

### ISSUE THREAD

**Issue by polarmutex** [polarmutex/beancount-language-server#161]
### Discussed in https://github.com/polarmutex/beancount-language-server/discussions/160

<div type='discussions-op-text'>

<sup>Originally posted by **DanielPower** May  1, 2022</sup>
I've tried the following installations:

- 1.0.2 from Cargo
- 1.0.2 from Arch User Repository
- 1.0.3 installed via nvim-lsp-installer (by modifying their install script, since their parser hasn't been updated for the new file name structure in 1.0.3).

LspInfo shows that the file I have open is of filetype: beancount. And it shows that the language server is executable, and set to autostart. But it does not start. Additionally, if I run `LspStart beancount` manually, nothing happens.

![1651453686](https://user-images.githubusercontent.com/12166320/166173113-33a65091-8c49-4016-b98f-ebe698635024.png)

I'm not aware of any logs that might have any relevant information, but would appreciate it if you have any advice.

Attached is the config I'm passing to lspconfig.

![1651453850](https://user-images.githubusercontent.com/12166320/166173168-5ab90aa7-3414-49b2-9814-25df6313173c.png)

I'm not sure what the `journalFile` is supposed to refer to. So that could be the problem, since mine is blank. If that needs to be populated, what should I point it to?</div>

**Comment by hateonion** [comment]
This should be fix now based on https://github.com/neovim/nvim-lspconfig/pull/1879 .
