### ISSUE TITLE
neovim nightly setup

### ISSUE THREAD

**Issue by crispgm** [polarmutex/beancount-language-server#28]
Hi there,

I am a big user of neovim nightly and beancount for PTA. Just notice that here is a beancount LS, and tried to setup followings lspconfig and your dotfiles. Unluckily it failed.

So I am here kindly request for a setup guide for neovim nightly.

Thanks very much.

**Comment by polarmutex** [comment]
I will update the documentation soon.

**Comment by polarmutex** [comment]
updated the readme with what I believe the setup instructions are for neovim. I plan on adding a config to the neovim lspconfig in the near future.

**Comment by crispgm** [comment]
> updated the readme with what I believe the setup instructions are for neovim. I plan on adding a config to the neovim lspconfig in the near future.

Thanks it works. `local util = require('lspconfig/util')` is required though.

**Comment by polarmutex** [comment]
fixed the readme
