### ISSUE TITLE
nvim-lspconfig and beancount-language-server

### ISSUE THREAD

**Issue by M1Sports20** [polarmutex/beancount-language-server#356]
It seems the default options in nvim-lspconfig doesn't work with the latest beancount-lsp.

The latest version of beancount-lsp has argument --stdio <stdio>  The nvim-lspconfig doesn't provide an argument to --stdio resulting in the following error:
[ERROR][2023-03-25 15:41:44] .../vim/lsp/rpc.lua:733    "rpc"   "beancount-language-server" "stderr"    "error: a value is required for '--stdio <stdio>' but none was supplied\n\nFor more information, try '--help'.\n"

I of course can also override the default cmd provided by nvim-lspconfig, but I dont' know what is expected as an argument here.

**Comment by onemoresuza** [comment]
Same error here:

> [START][2023-03-29 06:45:57] LSP logging initiated
> [ERROR][2023-03-29 06:45:57] .../vim/lsp/rpc.lua:734	"rpc"	"beancount-language-server"	"stderr"	"error: a value is required for '--stdio <stdio>' but none was supplied\n\nFor more information, try '--help'.\n"

The used configuration is:

``` lua
require("lspconfig").beancount.setup({
   init_options = {
      journal_file = "/path/to/real/journal/file",
   }
})
```

**Comment by polarmutex** [comment]
interesting, I will try to look at it tonight

DId this just happen recently? I did push an update in the last week or so

**Comment by M1Sports20** [comment]
Yes it happened when I upgraded to the latest version.

**Comment by peterhoeg** [comment]
I've seen the same thing with emacs. The workaround is just to pass any garbage argument after `--stdio` when launching `beancount-ls`.

**Comment by kmac** [comment]
Thanks @peterhoeg , I'm working around this with these custom options:

```    
   beancount = {
      cmd = { "beancount-language-server", "--stdio", "asdf" },
      init_options = {
        journal_file = "<path to my beancount file>",
      },
    },
```

**Comment by polarmutex** [comment]
should be fixed with v1.3.1 I did yesterday, sorry i missed this one

**Comment by peterhoeg** [comment]
I can confirm that works.

**Comment by polarmutex** [comment]
closing, if this is still an issue please reopen issue

**Comment by duarteocarmo** [comment]
@polarmutex  - where's this v1.3.1? 

Can't see it [here](https://crates.io/crates/beancount-language-server/versions )

**Comment by polarmutex** [comment]
should be able to find it on the releases page or pull from crates.io.  i am not sure how you install lsp servers on your machine.

**Comment by duarteocarmo** [comment]
You mean [here](https://crates.io/crates/beancount-language-server/versions)? The latest version is `v1.3.0`

I just do `cargo install xxxxxx`

**Comment by peterhoeg** [comment]
<https://github.com/polarmutex/beancount-language-server/releases>

**Comment by duarteocarmo** [comment]
Ah ok - you guys install straight from github! Thanks @peterhoeg

**Comment by peterhoeg** [comment]
> you guys install straight from github!

No, my distribution carries it: <https://github.com/NixOS/nixpkgs/commit/98d2146331f49640ebb3e852e78cca0aa023e020>

I haven’t installed anything directly from GH in *years*.

**Comment by duarteocarmo** [comment]
God damnit, I need to get into nix I see 😆 Thanks ahah

**Comment by polarmutex** [comment]
guess i missed uploading 1.3.1 to crates.io, should be there now
