### ISSUE TITLE
Make `--stdio` the default?

### ISSUE THREAD

**Issue by HappyEinara** [polarmutex/beancount-language-server#49]
Currently `<lspconfig>.beancount.setup` requires the following to be included:
```
cmd = {                                                                              
  "beancount-langserver",                                                            
  "--stdio",                                                                         
},            
```

It seems to me that if `--stdio` were the default behaviour on running `beancount-langserver` without arguments, then the integration would would out of the box without `cmd` with less mandatory configuration by the user: `cmd` could just be left out. LSP in nvim is already quite a steep learning curve; this might make life easier for new users?

**Comment by polarmutex** [comment]
fair point, we could change lspconfig to add the "--stdio" option too.

**Comment by polarmutex** [comment]
fixed in master, now the old typescript and rust versions have the same options to run
