### ISSUE TITLE
1.3.5 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [polarmutex/beancount-language-server#538]
👋 looks like 1.3.5 release was not completed, any reason why? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/180234

**Comment by polarmutex** [comment]
the macOS GitHub runner did not complete and I had to finish the release manually. I took off the pre-release tag right now

does homebrew need anything else to unblock them?

**Comment by chenrui333** [comment]
yeah, that should be it, thanks!
