### ISSUE TITLE
Installation failed on Arch Linux system

### ISSUE THREAD

**Issue by k12teach** [polarmutex/beancount-language-server#555]
Unable to install `beancount-language-server` on an Arch Linux system. 

```sh
$ cargo --version                                                   
cargo 1.81.0 (2dbb1af80 2024-08-20)

$ rustc --version      
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

Installation backtrace 

```sh 
cargo install beancount-language-server --verbose
```   
Backtrace attached. Unable to insert here. 
[debug_bll.txt](https://github.com/user-attachments/files/16982926/debug_bll.txt)

**Comment by devbydaniel** [comment]
Having the same issue
