### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by crispgm** [polarmutex/beancount-language-server#86]
```
npm install -g @bryall/beancount-langserver
```
prompts error, I guess it should be:

```
npm install -g beancount-language-server
```

**Comment by polarmutex** [comment]
sorry the README is really out of date, I will work on it soon

the original implementation was typescript and you can install it with as you found out "npm install beancount-langserver"

I am now implementing this in rust and I am wanting to add to rust package stores soon. For now you can install from source and run the rust version
